name: Deploy to npmjs

on:
  create:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 15
    - run: npm install
    - run: npm run build
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_ACCESS_TOKEN }}