name: Deploy to npmjs

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    if: github.event.deleted != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v6
      - run: pnpm install --frozen-lockfile
      - run: pnpm publish --filter solid-theme-provider --no-git-checks
